"""Create student profiles table

Revision ID: eef6817b4dd1
Revises: 2c05f29ab815
Create Date: 2026-08-20 22:23:45.403333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eef6817b4dd1'
down_revision: Union[str, Sequence[str], None] = '2c05f29ab815'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('college', sa.String(length=200), nullable=True),
    sa.Column('degree', sa.String(length=100), nullable=True),
    sa.Column('branch', sa.String(length=100), nullable=True),
    sa.Column('semester', sa.Integer(), nullable=True),
    sa.Column('cgpa', sa.Float(), nullable=True),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('github_url', sa.String(length=255), nullable=True),
    sa.Column('linkedin_url', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_student_profiles_id'), 'student_profiles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_profiles_id'), table_name='student_profiles')
    op.drop_table('student_profiles')
    # ### end Alembic commands ###
